### ISSUE TITLE
Option to follow 301/302 redirects

### ISSUE THREAD

**Issue by manuel-di-iorio** [bobby-brennan/rss-parser#21] opened 2017-02-07 11:06 UTC
Trying to parse http://bitcoinist.com/feed I got the error with message "Status code 301". 
Would you please add an option to automatically follow the redirects ?

**Comment by rub1e** [comment] 2017-02-07 11:23
Could this be achieved quite simply by using the [request](https://www.npmjs.com/package/request) package (which can follow redirects automatically)?

And then [this line](https://github.com/bobby-brennan/rss-parser/blob/master/index.js#L203) would change to something like:

`if (res.statusCode >= 400)`

Would something like that work?

**Comment by bobby-brennan** [comment] 2017-02-16 17:05
We've explored this before (https://github.com/bobby-brennan/rss-parser/issues/3).  The issue is that including the `request` package causes a lot of bloat in the browser distribution. Open to other ideas on handling redirects, but it's tricky.

**Comment by manuel-di-iorio** [comment] 2017-02-16 17:40
Raw code? Should be easy, just a simple recursive with a limit

**Comment by bobby-brennan** [comment] 2017-02-16 17:59
Sounds good to me.  Will happily accept a PR, otherwise I'll leave this open until I have a chance to get to it.

**Comment by bobby-brennan** [comment] 2017-03-27 18:45
Fixed in https://github.com/bobby-brennan/rss-parser/pull/23

Published as version 2.6.0

**Closed** 2017-03-27 18:45 UTC
